# Generated by Django 4.1.7 on 2023-05-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('user', models.CharField(max_length=50, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact_table',
            },
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('contact', models.BigIntegerField(default=False)),
                ('pickuptime', models.CharField(default=False, max_length=50)),
                ('tprice', models.BigIntegerField(default=None)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.carmodels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.registration')),
            ],
            options={
                'db_table': 'booking_table',
            },
        ),
    ]
